/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'slug': RouteRecordInfo<'slug', '/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'dashboard-admin-approvals': RouteRecordInfo<'dashboard-admin-approvals', '/dashboard/admin/approvals', Record<never, never>, Record<never, never>>,
    'dashboard-admin-approvals-preview-uuid': RouteRecordInfo<'dashboard-admin-approvals-preview-uuid', '/dashboard/admin/approvals/preview/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    'dashboard-admin-publications': RouteRecordInfo<'dashboard-admin-publications', '/dashboard/admin/publications', Record<never, never>, Record<never, never>>,
    'dashboard-admin-publications-components-contact-publisher-modal': RouteRecordInfo<'dashboard-admin-publications-components-contact-publisher-modal', '/dashboard/admin/publications/components/ContactPublisherModal', Record<never, never>, Record<never, never>>,
    'dashboard-chat': RouteRecordInfo<'dashboard-chat', '/dashboard/chat', Record<never, never>, Record<never, never>>,
    'dashboard-favorites-list': RouteRecordInfo<'dashboard-favorites-list', '/dashboard/favorites/list', Record<never, never>, Record<never, never>>,
    'dashboard-inquiries': RouteRecordInfo<'dashboard-inquiries', '/dashboard/inquiries', Record<never, never>, Record<never, never>>,
    'dashboard-inquiries-components-seller-chat-modal': RouteRecordInfo<'dashboard-inquiries-components-seller-chat-modal', '/dashboard/inquiries/components/SellerChatModal', Record<never, never>, Record<never, never>>,
    'dashboard-publications-components-step-basic-info': RouteRecordInfo<'dashboard-publications-components-step-basic-info', '/dashboard/publications/components/StepBasicInfo', Record<never, never>, Record<never, never>>,
    'dashboard-publications-components-step-documentation': RouteRecordInfo<'dashboard-publications-components-step-documentation', '/dashboard/publications/components/StepDocumentation', Record<never, never>, Record<never, never>>,
    'dashboard-publications-components-step-location-condition': RouteRecordInfo<'dashboard-publications-components-step-location-condition', '/dashboard/publications/components/StepLocationCondition', Record<never, never>, Record<never, never>>,
    'dashboard-publications-components-step-media': RouteRecordInfo<'dashboard-publications-components-step-media', '/dashboard/publications/components/StepMedia', Record<never, never>, Record<never, never>>,
    'dashboard-publications-components-step-tech-specs': RouteRecordInfo<'dashboard-publications-components-step-tech-specs', '/dashboard/publications/components/StepTechSpecs', Record<never, never>, Record<never, never>>,
    'dashboard-publications-components-step-type-selection': RouteRecordInfo<'dashboard-publications-components-step-type-selection', '/dashboard/publications/components/StepTypeSelection', Record<never, never>, Record<never, never>>,
    'dashboard-publications-offers-received': RouteRecordInfo<'dashboard-publications-offers-received', '/dashboard/publications/offers-received', Record<never, never>, Record<never, never>>,
    'dashboard-publications-publication-add': RouteRecordInfo<'dashboard-publications-publication-add', '/dashboard/publications/publication/add', Record<never, never>, Record<never, never>>,
    'dashboard-publications-publication-edit-uuid': RouteRecordInfo<'dashboard-publications-publication-edit-uuid', '/dashboard/publications/publication/edit/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    'dashboard-publications-publication-list': RouteRecordInfo<'dashboard-publications-publication-list', '/dashboard/publications/publication/list', Record<never, never>, Record<never, never>>,
    'dashboard-publications-publication-questions-uuid': RouteRecordInfo<'dashboard-publications-publication-questions-uuid', '/dashboard/publications/publication/questions/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    'dashboard-publications-questions': RouteRecordInfo<'dashboard-publications-questions', '/dashboard/publications/questions', Record<never, never>, Record<never, never>>,
    'dashboard-publications-sales': RouteRecordInfo<'dashboard-publications-sales', '/dashboard/publications/sales', Record<never, never>, Record<never, never>>,
    'dashboard-publications-sales-uuid': RouteRecordInfo<'dashboard-publications-sales-uuid', '/dashboard/publications/sales/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    'dashboard-purchases': RouteRecordInfo<'dashboard-purchases', '/dashboard/purchases', Record<never, never>, Record<never, never>>,
    'dashboard-purchases-uuid': RouteRecordInfo<'dashboard-purchases-uuid', '/dashboard/purchases/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    'dashboard-purchases-chat-uuid': RouteRecordInfo<'dashboard-purchases-chat-uuid', '/dashboard/purchases/chat/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    'dashboard-purchases-favorites': RouteRecordInfo<'dashboard-purchases-favorites', '/dashboard/purchases/favorites', Record<never, never>, Record<never, never>>,
    'dashboard-purchases-list': RouteRecordInfo<'dashboard-purchases-list', '/dashboard/purchases/list', Record<never, never>, Record<never, never>>,
    'dashboard-purchases-offers-sent': RouteRecordInfo<'dashboard-purchases-offers-sent', '/dashboard/purchases/offers-sent', Record<never, never>, Record<never, never>>,
    'dashboard-purchases-opinions': RouteRecordInfo<'dashboard-purchases-opinions', '/dashboard/purchases/opinions', Record<never, never>, Record<never, never>>,
    'dashboard-purchases-purchases': RouteRecordInfo<'dashboard-purchases-purchases', '/dashboard/purchases/purchases', Record<never, never>, Record<never, never>>,
    'dashboard-purchases-questions': RouteRecordInfo<'dashboard-purchases-questions', '/dashboard/purchases/questions', Record<never, never>, Record<never, never>>,
    'dashboard-questions-list': RouteRecordInfo<'dashboard-questions-list', '/dashboard/questions/list', Record<never, never>, Record<never, never>>,
    'dashboard-user-account': RouteRecordInfo<'dashboard-user-account', '/dashboard/user/account', Record<never, never>, Record<never, never>>,
    'dashboard-user-company': RouteRecordInfo<'dashboard-user-company', '/dashboard/user/company', Record<never, never>, Record<never, never>>,
    'dashboard-user-list': RouteRecordInfo<'dashboard-user-list', '/dashboard/user/list', Record<never, never>, Record<never, never>>,
    'dashboard-user-profile': RouteRecordInfo<'dashboard-user-profile', '/dashboard/user/profile', Record<never, never>, Record<never, never>>,
    'dashboard-user-view-id': RouteRecordInfo<'dashboard-user-view-id', '/dashboard/user/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'public-store': RouteRecordInfo<'public-store', '/public-store', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'reset-password': RouteRecordInfo<'reset-password', '/reset-password', Record<never, never>, Record<never, never>>,
    'store': RouteRecordInfo<'store', '/store', Record<never, never>, Record<never, never>>,
    'store-components-chat-inline': RouteRecordInfo<'store-components-chat-inline', '/store/components/ChatInline', Record<never, never>, Record<never, never>>,
    'store-components-chat-modal': RouteRecordInfo<'store-components-chat-modal', '/store/components/ChatModal', Record<never, never>, Record<never, never>>,
    'store-components-empty-state': RouteRecordInfo<'store-components-empty-state', '/store/components/EmptyState', Record<never, never>, Record<never, never>>,
    'store-components-login-modal': RouteRecordInfo<'store-components-login-modal', '/store/components/LoginModal', Record<never, never>, Record<never, never>>,
    'store-components-offer-modal': RouteRecordInfo<'store-components-offer-modal', '/store/components/OfferModal', Record<never, never>, Record<never, never>>,
    'store-components-pagination-controls': RouteRecordInfo<'store-components-pagination-controls', '/store/components/PaginationControls', Record<never, never>, Record<never, never>>,
    'store-components-product-details': RouteRecordInfo<'store-components-product-details', '/store/components/ProductDetails', Record<never, never>, Record<never, never>>,
    'store-components-product-docs': RouteRecordInfo<'store-components-product-docs', '/store/components/ProductDocs', Record<never, never>, Record<never, never>>,
    'store-components-product-image': RouteRecordInfo<'store-components-product-image', '/store/components/ProductImage', Record<never, never>, Record<never, never>>,
    'store-components-publicacion-info': RouteRecordInfo<'store-components-publicacion-info', '/store/components/PublicacionInfo', Record<never, never>, Record<never, never>>,
    'store-components-publicacion-items': RouteRecordInfo<'store-components-publicacion-items', '/store/components/PublicacionItems', Record<never, never>, Record<never, never>>,
    'store-components-publicacion-questions': RouteRecordInfo<'store-components-publicacion-questions', '/store/components/PublicacionQuestions', Record<never, never>, Record<never, never>>,
    'store-components-related-products': RouteRecordInfo<'store-components-related-products', '/store/components/RelatedProducts', Record<never, never>, Record<never, never>>,
    'store-components-search-bar': RouteRecordInfo<'store-components-search-bar', '/store/components/SearchBar', Record<never, never>, Record<never, never>>,
    'store-components-tienda-filters': RouteRecordInfo<'store-components-tienda-filters', '/store/components/TiendaFilters', Record<never, never>, Record<never, never>>,
  }
}
