/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'access-control': RouteRecordInfo<'access-control', '/access-control', Record<never, never>, Record<never, never>>,
    'apps-chat': RouteRecordInfo<'apps-chat', '/apps/chat', Record<never, never>, Record<never, never>>,
    'apps-favorites-list': RouteRecordInfo<'apps-favorites-list', '/apps/favorites/list', Record<never, never>, Record<never, never>>,
    'apps-inquiries': RouteRecordInfo<'apps-inquiries', '/apps/inquiries', Record<never, never>, Record<never, never>>,
    'apps-inquiries-components-seller-chat-modal': RouteRecordInfo<'apps-inquiries-components-seller-chat-modal', '/apps/inquiries/components/SellerChatModal', Record<never, never>, Record<never, never>>,
    'apps-invoice-add': RouteRecordInfo<'apps-invoice-add', '/apps/invoice/add', Record<never, never>, Record<never, never>>,
    'apps-invoice-edit-id': RouteRecordInfo<'apps-invoice-edit-id', '/apps/invoice/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-invoice-list': RouteRecordInfo<'apps-invoice-list', '/apps/invoice/list', Record<never, never>, Record<never, never>>,
    'apps-invoice-preview-id': RouteRecordInfo<'apps-invoice-preview-id', '/apps/invoice/preview/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'apps-publications-offers-received': RouteRecordInfo<'apps-publications-offers-received', '/apps/publications/offers-received', Record<never, never>, Record<never, never>>,
    'apps-publications-publication-add': RouteRecordInfo<'apps-publications-publication-add', '/apps/publications/publication/add', Record<never, never>, Record<never, never>>,
    'apps-publications-publication-add-form': RouteRecordInfo<'apps-publications-publication-add-form', '/apps/publications/publication/add/form', Record<never, never>, Record<never, never>>,
    'apps-publications-publication-add-select-type': RouteRecordInfo<'apps-publications-publication-add-select-type', '/apps/publications/publication/add/select-type', Record<never, never>, Record<never, never>>,
    'apps-publications-publication-edit-uuid': RouteRecordInfo<'apps-publications-publication-edit-uuid', '/apps/publications/publication/edit/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    'apps-publications-publication-list': RouteRecordInfo<'apps-publications-publication-list', '/apps/publications/publication/list', Record<never, never>, Record<never, never>>,
    'apps-publications-publication-questions-uuid': RouteRecordInfo<'apps-publications-publication-questions-uuid', '/apps/publications/publication/questions/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    'apps-publications-questions': RouteRecordInfo<'apps-publications-questions', '/apps/publications/questions', Record<never, never>, Record<never, never>>,
    'apps-publications-sales': RouteRecordInfo<'apps-publications-sales', '/apps/publications/sales', Record<never, never>, Record<never, never>>,
    'apps-publications-sales-uuid': RouteRecordInfo<'apps-publications-sales-uuid', '/apps/publications/sales/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    'apps-purchases': RouteRecordInfo<'apps-purchases', '/apps/purchases', Record<never, never>, Record<never, never>>,
    'apps-purchases-uuid': RouteRecordInfo<'apps-purchases-uuid', '/apps/purchases/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    'apps-purchases-chat-uuid': RouteRecordInfo<'apps-purchases-chat-uuid', '/apps/purchases/chat/:uuid', { uuid: ParamValue<true> }, { uuid: ParamValue<false> }>,
    'apps-purchases-favorites': RouteRecordInfo<'apps-purchases-favorites', '/apps/purchases/favorites', Record<never, never>, Record<never, never>>,
    'apps-purchases-list': RouteRecordInfo<'apps-purchases-list', '/apps/purchases/list', Record<never, never>, Record<never, never>>,
    'apps-purchases-offers-sent': RouteRecordInfo<'apps-purchases-offers-sent', '/apps/purchases/offers-sent', Record<never, never>, Record<never, never>>,
    'apps-purchases-opinions': RouteRecordInfo<'apps-purchases-opinions', '/apps/purchases/opinions', Record<never, never>, Record<never, never>>,
    'apps-purchases-purchases': RouteRecordInfo<'apps-purchases-purchases', '/apps/purchases/purchases', Record<never, never>, Record<never, never>>,
    'apps-purchases-questions': RouteRecordInfo<'apps-purchases-questions', '/apps/purchases/questions', Record<never, never>, Record<never, never>>,
    'apps-questions-list': RouteRecordInfo<'apps-questions-list', '/apps/questions/list', Record<never, never>, Record<never, never>>,
    'apps-user-account': RouteRecordInfo<'apps-user-account', '/apps/user/account', Record<never, never>, Record<never, never>>,
    'apps-user-company': RouteRecordInfo<'apps-user-company', '/apps/user/company', Record<never, never>, Record<never, never>>,
    'apps-user-list': RouteRecordInfo<'apps-user-list', '/apps/user/list', Record<never, never>, Record<never, never>>,
    'apps-user-profile': RouteRecordInfo<'apps-user-profile', '/apps/user/profile', Record<never, never>, Record<never, never>>,
    'apps-user-stats': RouteRecordInfo<'apps-user-stats', '/apps/user/stats', Record<never, never>, Record<never, never>>,
    'apps-user-view-id': RouteRecordInfo<'apps-user-view-id', '/apps/user/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'dashboards-components-offers-received': RouteRecordInfo<'dashboards-components-offers-received', '/dashboards/components/OffersReceived', Record<never, never>, Record<never, never>>,
    'dashboards-components-offers-sent': RouteRecordInfo<'dashboards-components-offers-sent', '/dashboards/components/OffersSent', Record<never, never>, Record<never, never>>,
    'dashboards-publications': RouteRecordInfo<'dashboards-publications', '/dashboards/publications', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'store': RouteRecordInfo<'store', '/store', Record<never, never>, Record<never, never>>,
    'store-slug': RouteRecordInfo<'store-slug', '/store/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    'store-components-chat-inline': RouteRecordInfo<'store-components-chat-inline', '/store/components/ChatInline', Record<never, never>, Record<never, never>>,
    'store-components-chat-modal': RouteRecordInfo<'store-components-chat-modal', '/store/components/ChatModal', Record<never, never>, Record<never, never>>,
    'store-components-offer-modal': RouteRecordInfo<'store-components-offer-modal', '/store/components/OfferModal', Record<never, never>, Record<never, never>>,
    'store-components-pagination-controls': RouteRecordInfo<'store-components-pagination-controls', '/store/components/PaginationControls', Record<never, never>, Record<never, never>>,
    'store-components-product-details': RouteRecordInfo<'store-components-product-details', '/store/components/ProductDetails', Record<never, never>, Record<never, never>>,
    'store-components-product-docs': RouteRecordInfo<'store-components-product-docs', '/store/components/ProductDocs', Record<never, never>, Record<never, never>>,
    'store-components-product-image': RouteRecordInfo<'store-components-product-image', '/store/components/ProductImage', Record<never, never>, Record<never, never>>,
    'store-components-publicacion-info': RouteRecordInfo<'store-components-publicacion-info', '/store/components/PublicacionInfo', Record<never, never>, Record<never, never>>,
    'store-components-publicacion-items': RouteRecordInfo<'store-components-publicacion-items', '/store/components/PublicacionItems', Record<never, never>, Record<never, never>>,
    'store-components-publicacion-questions': RouteRecordInfo<'store-components-publicacion-questions', '/store/components/PublicacionQuestions', Record<never, never>, Record<never, never>>,
    'store-components-related-products': RouteRecordInfo<'store-components-related-products', '/store/components/RelatedProducts', Record<never, never>, Record<never, never>>,
    'store-components-search-bar': RouteRecordInfo<'store-components-search-bar', '/store/components/SearchBar', Record<never, never>, Record<never, never>>,
    'store-components-tienda-filters': RouteRecordInfo<'store-components-tienda-filters', '/store/components/TiendaFilters', Record<never, never>, Record<never, never>>,
  }
}
